create table authors (id bigint generated by default as identity, name varchar(255), primary key (id));
create table books (id bigint generated by default as identity, title varchar(40) not null, author_id bigint, primary key (id));
create table books_genres (book_id bigint not null, genres_id bigint not null, primary key (book_id, genres_id));
create table comments (id bigint generated by default as identity, text varchar(255), book_id bigint, user_id bigint, primary key (id));
create table genres (id bigint generated by default as identity, name varchar(255), primary key (id));
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id));
alter table books add constraint FKfjixh2vym2cvfj3ufxj91jem7 foreign key (author_id) references authors;
alter table books_genres add constraint FKd69nnd4vn4ql5pp5i0fmmr7de foreign key (genres_id) references genres;
alter table books_genres add constraint FKlv42b6uemg63q27om39jjbt9o foreign key (book_id) references books;
alter table comments add constraint FK1ey8gegnanvybix5a025vepf4 foreign key (book_id) references books;
alter table comments add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users;


create table acl_sid(
  id bigserial not null primary key,
  principal boolean not null,
  sid varchar(100) not null,
  constraint unique_uk_1 unique(sid,principal));

create table acl_class(
  id bigserial not null primary key,
  class varchar(100) not null,
  constraint unique_uk_2 unique(class));

create table acl_object_identity(
  id bigserial primary key,
  object_id_class bigint not null,
  object_id_identity bigint not null,
  parent_object bigint,
  owner_sid bigint,
  entries_inheriting boolean not null,
  constraint unique_uk_3 unique(object_id_class,object_id_identity),
  constraint foreign_fk_1 foreign key(parent_object) references acl_object_identity(id),
  constraint foreign_fk_2 foreign key(object_id_class) references acl_class(id),
  constraint foreign_fk_3 foreign key(owner_sid) references acl_sid(id));

create table acl_entry(
  id bigserial primary key,
  acl_object_identity bigint not null,
  ace_order int not null,
  sid bigint not null,
  mask integer not null,
  granting boolean not null,
  audit_success boolean not null,
  audit_failure boolean not null,
  constraint unique_uk_4 unique(acl_object_identity,ace_order),
  constraint foreign_fk_4 foreign key(acl_object_identity)
      references acl_object_identity(id),
  constraint foreign_fk_5 foreign key(sid) references acl_sid(id));